version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_api
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  mysql:
    image: mysql:5.7 
    container_name: sample_course_mysql
    command: mysqld --user=root
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=course
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
